import ProtectedRoutes from "@/components/ProtectedRoutes";
import { isValidToken } from "@/lib/utils";
import type { Metadata } from "next";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = cookies().get("token")?.value;
  const { validToken, userData } = await isValidToken(token as string);
  return (
    <ProtectedRoutes isValidToken={validToken} userData={userData}>
      {children}
    </ProtectedRoutes>
  );
}
